// Deadline reminders. IMPORTANT LIMITATION (shown in the UI, not just here):
// there's no push server, so browser notifications only fire while this
// tab stays open in the browser the whole time until the deadline. The
// .ics download is the reliable fallback - it works through the user's
// own calendar app regardless of whether the site is open.

const REMINDER_OFFSETS_MS = [
  { label: "24 שעות", ms: 24 * 60 * 60 * 1000 },
  { label: "3 שעות", ms: 3 * 60 * 60 * 1000 },
  { label: "שעה", ms: 1 * 60 * 60 * 1000 },
];

let scheduledTimers = [];

function clearScheduled() {
  scheduledTimers.forEach(clearTimeout);
  scheduledTimers = [];
}

export function scheduleBrowserReminders(deadlineIso, gwLabel) {
  clearScheduled();
  const deadline = new Date(deadlineIso).getTime();
  const now = Date.now();
  let scheduledCount = 0;

  for (const { label, ms } of REMINDER_OFFSETS_MS) {
    const fireAt = deadline - ms;
    const delay = fireAt - now;
    if (delay <= 0) continue;
    const timerId = setTimeout(() => {
      if (Notification.permission === "granted") {
        new Notification(`דדליין FPL בעוד ${label}`, {
          body: `${gwLabel} ננעל בעוד ${label}. בדוק את הקבוצה שלך!`,
          icon: "⚽",
        });
      }
    }, delay);
    scheduledTimers.push(timerId);
    scheduledCount++;
  }
  return scheduledCount;
}

function icsEscape(text) {
  return text.replace(/\\/g, "\\\\").replace(/,/g, "\\,").replace(/;/g, "\\;");
}

function toIcsUtc(date) {
  return date.toISOString().replace(/[-:]/g, "").split(".")[0] + "Z";
}

export function buildIcs(deadlineIso, gwLabel) {
  const deadline = new Date(deadlineIso);
  const end = new Date(deadline.getTime() + 15 * 60 * 1000);
  const now = new Date();
  const uid = `fpl-deadline-${deadline.getTime()}@fpl-analyzer`;

  const lines = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//FPL Analyzer//he",
    "BEGIN:VEVENT",
    `UID:${uid}`,
    `DTSTAMP:${toIcsUtc(now)}`,
    `DTSTART:${toIcsUtc(deadline)}`,
    `DTEND:${toIcsUtc(end)}`,
    `SUMMARY:${icsEscape(`דדליין FPL - ${gwLabel}`)}`,
    `DESCRIPTION:${icsEscape(`דדליין להעברות ובחירת קבוצה ל${gwLabel} בפנטזי פרימייר ליג`)}`,
    "BEGIN:VALARM", "ACTION:DISPLAY", "DESCRIPTION:דדליין FPL בעוד יום", "TRIGGER:-P1D", "END:VALARM",
    "BEGIN:VALARM", "ACTION:DISPLAY", "DESCRIPTION:דדליין FPL בעוד 3 שעות", "TRIGGER:-PT3H", "END:VALARM",
    "BEGIN:VALARM", "ACTION:DISPLAY", "DESCRIPTION:דדליין FPL בעוד שעה", "TRIGGER:-PT1H", "END:VALARM",
    "END:VEVENT",
    "END:VCALENDAR",
  ];
  return lines.join("\r\n");
}

/** Google's own "quick add" template URL - opens calendar.google.com
 * with the event pre-filled, the user still clicks Save themselves in
 * Google's UI. No API key/OAuth needed, and unlike an .ics file import
 * (which Google Calendar's importer is known to strip custom VALARMs
 * from), an event created this way is a normal Google Calendar event
 * that picks up whatever default reminders the user has configured
 * for their calendar - set those once in Google Calendar's settings
 * and every deadline added this way notifies reliably from then on. */
/** The URL of the full-season deadlines feed (scripts/deadlines_ics.py,
 * regenerated by the daily pipeline from bootstrap.json - all 38
 * gameweeks). Built relative to the current page so it works the same
 * on GitHub Pages, a custom domain, or a local test server. Meant to
 * be subscribed to once (Google Calendar: Settings > Add calendar >
 * From URL) rather than downloaded - a subscription re-polls this URL
 * on its own and picks up future deadline changes automatically. */
export function deadlinesFeedUrl() {
  return new URL("data/deadlines.ics", location.href).href;
}

export function googleCalendarUrl(deadlineIso, gwLabel) {
  const deadline = new Date(deadlineIso);
  const end = new Date(deadline.getTime() + 15 * 60 * 1000);
  const params = new URLSearchParams({
    action: "TEMPLATE",
    text: `דדליין FPL - ${gwLabel}`,
    dates: `${toIcsUtc(deadline)}/${toIcsUtc(end)}`,
    details: `דדליין להעברות ובחירת קבוצה ל${gwLabel} בפנטזי פרימייר ליג`,
  });
  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

export function downloadIcs(deadlineIso, gwLabel) {
  const ics = buildIcs(deadlineIso, gwLabel);
  const blob = new Blob([ics], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "fpl-deadline.ics";
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}

function formatTimeLeft(deadlineIso) {
  const diff = new Date(deadlineIso).getTime() - Date.now();
  if (diff <= 0) return "הדדליין עבר";
  const days = Math.floor(diff / (24 * 60 * 60 * 1000));
  const hours = Math.floor((diff % (24 * 60 * 60 * 1000)) / (60 * 60 * 1000));
  if (days > 0) return `${days} ימים ו-${hours} שעות`;
  return `${hours} שעות`;
}

export function renderReminderWidget(container, meta) {
  if (!meta?.deadline_time) {
    container.innerHTML = "";
    return;
  }
  const gwLabel = `מחזור ${meta.gw_next ?? meta.gameweek ?? ""}`;
  const supported = "Notification" in window;
  const permission = supported ? Notification.permission : "unsupported";

  container.innerHTML = `
    <div class="reminder-widget">
      <div class="reminder-info">
        <strong>דדליין ${gwLabel}:</strong> ${formatTimeLeft(meta.deadline_time)}
        <div class="reminder-caveat">
          התראות דפדפן עובדות רק כשהטאב הזה פתוח (אין שרת push) - לתזכורת אמינה, תוסיף ליומן.
          "Google Calendar" פותח אירוע מוכן ל-Google עצמו (בלי צורך בהתחברות/הרשאות) - הוא יקבל את
          התזכורות שהגדרת כברירת מחדל ל-Google Calendar שלך.
        </div>
      </div>
      <div class="reminder-actions">
        <button id="btnBrowserNotif" class="reminder-btn">
          ${permission === "granted" ? "✓ התראות דפדפן פעילות" : "🔔 הפעל התראות דפדפן"}
        </button>
        <button id="btnGoogleCal" class="reminder-btn secondary">📅 הוסף ל-Google Calendar</button>
        <button id="btnIcsDownload" class="reminder-btn secondary">הוסף ליומן (ICS)</button>
      </div>
      <div class="reminder-subscribe">
        <div class="reminder-caveat">
          <strong>מנוי אוטומטי לכל העונה</strong> (חד-פעמי, בלי ללחוץ בכל מחזור): ב-Google Calendar
          פתח הגדרות ← "הוספת יומן" ← "מיומן URL" והדבק את הקישור. Google תמשוך את כל 38 הדדליינים
          ותעדכן אותם לבד אם לוח המשחקים משתנה (מתרענן כל 12-24 שעות בערך, לא מיידי). את ההתראות
          עצמן קובעים פעם אחת עבור היומן הזה בהגדרות שלו ב-Google Calendar.
        </div>
        <div class="reminder-actions">
          <code id="feedUrlText" class="feed-url"></code>
          <button id="btnCopyFeed" class="reminder-btn secondary">העתק קישור</button>
        </div>
      </div>
    </div>
  `;

  const notifBtn = document.getElementById("btnBrowserNotif");
  const googleBtn = document.getElementById("btnGoogleCal");
  const icsBtn = document.getElementById("btnIcsDownload");
  const feedUrlText = document.getElementById("feedUrlText");
  const copyFeedBtn = document.getElementById("btnCopyFeed");
  const feedUrl = deadlinesFeedUrl();
  feedUrlText.textContent = feedUrl;

  if (!supported) {
    notifBtn.disabled = true;
    notifBtn.textContent = "התראות דפדפן לא נתמכות";
  } else if (permission === "granted") {
    scheduleBrowserReminders(meta.deadline_time, gwLabel);
  }

  notifBtn.addEventListener("click", async () => {
    if (!supported) return;
    const result = await Notification.requestPermission();
    if (result === "granted") {
      const count = scheduleBrowserReminders(meta.deadline_time, gwLabel);
      notifBtn.textContent = "✓ התראות דפדפן פעילות";
      notifBtn.title = `${count} תזכורות מתוזמנות`;
    } else {
      notifBtn.textContent = "🔔 הרשאה נדחתה - נסה שוב";
    }
  });

  googleBtn.addEventListener("click", () => {
    window.open(googleCalendarUrl(meta.deadline_time, gwLabel), "_blank", "noopener");
  });
  icsBtn.addEventListener("click", () => downloadIcs(meta.deadline_time, gwLabel));

  copyFeedBtn.addEventListener("click", async () => {
    try {
      await navigator.clipboard.writeText(feedUrl);
      copyFeedBtn.textContent = "✓ הועתק";
    } catch {
      copyFeedBtn.textContent = "לא ניתן להעתיק - סמן ידנית";
    }
    setTimeout(() => { copyFeedBtn.textContent = "העתק קישור"; }, 2500);
  });
}
